// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("bs-platform/lib/js/js_math.js");

var rollD6 = Js_math.random_int(1, 6);

function genRolls(lower, upper) {
  
}

exports.rollD6 = rollD6;
exports.genRolls = genRolls;
/* rollD6 Not a pure module */
