// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var NpcGen$Npcgen = require("../src/NpcGen.bs.js");

Jest.describe("NpcGen", (function (param) {
        Jest.test("rollD6", (function (param) {
                return Jest.Expect.toBeLessThan(6, Jest.Expect.expect(NpcGen$Npcgen.rollD6(undefined)));
              }));
        return Jest.test("rollD6", (function (param) {
                      return Jest.Expect.toBeGreaterThan(0, Jest.Expect.expect(NpcGen$Npcgen.rollD6(undefined)));
                    }));
      }));

/*  Not a pure module */
